title: Dan Tocchini
purpose:
  - name: follow
    url: 'https://twitter.com/d4tocchini'
    item: 86dafa44-5930-4ca9-9ebe-9e3b5a1f5e6d
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
color:
  saturation: 0.1875
  brandStrength: 0.9375
  lightness: 0.875
  brandColors:
    - '#312704'
    - '#6E1603'
    - '#BD2F0E'
    - '#FB885B'
    - '#765C30'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-61994900-1
  facebook: null
favicon: 'https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/favlogos/d-favicon.png'
name: D4
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.97271
layout_spectrum: 0.3711063
