name: D4
favicon: "https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/favlogos/d-favicon.png"
layout_spectrum: 0.8
typography_spectrum: 0.8
color:
  brandColors: 
    - "#66ccc0"
    - "#5f4d5f"
    - "#d12164"
    - "#dbc6bc"
    - "#faefda"
purpose: 
  - 
    name: "follow"
    item: "2f4afb84-83fd-4fd2-a8db-1e801cdea62f"
    url: "https://twitter.com/d4tocchini"
analytics:
  google: UA-61994900-1
