name: D4
title: "Dan Tocchini"
favicon: "https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/favlogos/d-favicon.png"
layout_spectrum: 0.8
typography_spectrum: 0.97
color:
  brandColors: 
    - "#66ccc0"
    - "#5f4d5f"
    - "#d12164"
    - "#dbc6bc"
    - "#faefda"
purpose: 
  - 
    name: "follow"
    item: "86dafa44-5930-4ca9-9ebe-9e3b5a1f5e6d"
    url: "https://twitter.com/d4tocchini"
analytics:
  google: UA-61994900-1
