typography_spectrum: 1
color:
  brandColors:
    - '#181d23'
    - '#314b2a'
    - '#49627f'
    - '#5e8235'
    - '#82a98d'
  brandStrength: 0.7131612475495785
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6775344042107463
analytics:
  google: UA-61994900-1
  facebook: null
  twitter: null
name: D4
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: cf8bc19e-d023-4246-93ad-84dfdf47ce58
    url: 2016-05-14-this-is-a-new-post.html
    name: Head over heals for AI
    type: content
  - id: 'https://projects.invisionapp.com/d/main#/projects/6191786'
    url: 'https://projects.invisionapp.com/d/main#/projects/6191786'
    name: Super Awesome
    type: external
  - id: 817daa93-5db5-4bcc-91de-e8b08d1c1ed0
    url: >-
      2015-12-21-from-science-fiction-to-reality-the-evolution-of-artificial.html
    name: 'From Science Fiction to Reality: The Evolution of Artificial Intelligence'
    type: content
favicon: 'https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/favlogos/d-favicon.png'
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
title: Dan Tocchini
purpose:
  - name: follow
    url: 'https://twitter.com/d4tocchini'
    item: 86dafa44-5930-4ca9-9ebe-9e3b5a1f5e6d
